version: "3.8"
services:
  db:
    container_name: marketing_db
    image: postgres:16.6-bookworm
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_EXTENSIONS: citext ,uuid-ossp
    ports:
      - ${POSTGRES_BIND_PORT}:5432
    volumes:
      - ${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql

  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: audioconvert_proxy
    restart: unless-stopped
    ports:
      # Runtime configuration
      # - "9484:80"
      # - "81:81"
      - "9484:443"

      # # Local configuration
      # - "80:80"
      # - "81:81"
      # - "443:443"

    volumes:
      - "${NGINX_FILE_VOLUME_PATH}:/data"
      - "${LETSENCRYPT_FILE_VOLUME_PATH}:/etc/letsencrypt"
    network_mode: host

  app:
    logging:
      options:
        max-size: 10m
    container_name: marketing_bsm
    build:
      context: .
    image: marketing_bsm_image
    network_mode: host
    depends_on:
      - db
      - nginx
      - minio
    ports:
      - "4000:4000"

    environment:
      MIX_ENV: ${MIX_ENV}
      PORT: "4000"
      PHX_HOST: ${PHX_HOST}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      PROJECT_URL_CLIENT: ${PROJECT_URL_CLIENT}
      PROJECT_URL_SERVER: ${PROJECT_URL_SERVER}
      PROJECT_URL_SOCKET: ${PROJECT_URL_SOCKET}
      PROJECT_URL_MEDIA: ${PROJECT_URL_MEDIA}
      PROJECT_OTP_LENGTH: ${PROJECT_OTP_LENGTH}
      PROJECT_OTP_EXPIRY: ${PROJECT_OTP_EXPIRY}
      PROJECT_OTP_CHARACTER_SET: ${PROJECT_OTP_CHARACTER_SET}
      S3_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
      S3_BUCKET: ${MINIO_S3_BUCKET}
      S3_REGION: ${MINIO_S3_REGION}
      S3_HOST: ${S3_HOST}
      S3_PORT: ${S3_PORT}
      S3_SCHEME: ${S3_SCHEME}

      JWT_SECRET: ${JWT_SECRET}
      RELEASE_COOKIE: ${RELEASE_COOKIE}
      RELEASE_NODE: ${RELEASE_NODE}
      RELEASE_DISTRIBUTION: ${RELEASE_DISTRIBUTION}
      DATABASE_URL: ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_BIND_PORT}/${DATABASE_NAME}

  minio:
    container_name: minio_cont
    image: quay.io/minio/minio:RELEASE.2024-01-18T22-51-28Z
    #command: server --console-address ":9001" http://minio/data
    command: server /data --address ":${S3_PORT}" --console-address ":${S3_WEB_CLIENT_PORT}"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
      MINIO_DEFAULT_BUCKETS: ${S3_BUCKET}
      MINIO_ADDRESS: ${S3_PORT}
      MINIO_CONSOLE_ADDRESS: ${S3_WEB_CLIENT_PORT}
    ports:
      - ${S3_PORT}:${S3_PORT}
      - ${S3_WEB_CLIENT_PORT}:${S3_WEB_CLIENT_PORT}
    network_mode: host
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "${S3_FILE_VOLUME_PATH}:/data"

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      device: ${POSTGRES_VOLUME_PATH}

  nginx_volume:
    driver: local
    driver_opts:
      type: none
      device: ${NGINX_FILE_VOLUME_PATH}
networks:
  amqp_network:
    driver: bridge
