defmodule Marketingbsm.Repo.Migrations.Checkinsprojects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:checkouts) do
      modify :project_id,
             references(:projectgeneral,
               column: :id,
               name: "checkouts_project_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:checkouts, [:project_id])

    alter table(:checkins) do
      modify :project_id,
             references(:projectgeneral,
               column: :id,
               name: "checkins_project_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:checkins, [:project_id])
  end

  def down do
    drop_if_exists index(:checkins, [:project_id])

    drop constraint(:checkins, "checkins_project_id_fkey")

    alter table(:checkins) do
      modify :project_id, :uuid
    end

    drop_if_exists index(:checkouts, [:project_id])

    drop constraint(:checkouts, "checkouts_project_id_fkey")

    alter table(:checkouts) do
      modify :project_id, :uuid
    end
  end
end
