defmodule Marketingbsm.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("ambassadors", "ambassadors_pkey")

    alter table(:ambassadors) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end
  end

  def down do
    drop constraint("ambassadors", "ambassadors_pkey")

    alter table(:ambassadors) do
      remove :id
    end
  end
end
