defmodule Marketingbsm.Repo.Migrations.GenerateTime do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:checkins) do
      add :create_time, :time, null: false
    end
  end

  def down do
    alter table(:checkins) do
      remove :create_time
    end
  end
end
