defmodule Marketingbsm.Repo.Migrations.Registryproject do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:registries) do
      modify :project_id,
             references(:projectgeneral,
               column: :id,
               name: "registries_project_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:registries, [:project_id])
  end

  def down do
    drop_if_exists index(:registries, [:project_id])

    drop constraint(:registries, "registries_project_id_fkey")

    alter table(:registries) do
      modify :project_id, :uuid
    end
  end
end
