defmodule Marketingbsm.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :hashed_password, :text, null: false
      add :name, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :project_id, :uuid, null: false
      add :field_1, :text
      add :field_2, :text
      add :field_3, :text
      add :field_4, :text
      add :field_5, :text
      add :field_6, :text
      add :field_7, :text
      add :field_8, :text
      add :field_9, :text
      add :field_10, :text
      add :field_11, :text
      add :field_12, :text
      add :field_13, :text
      add :field_14, :text
      add :field_15, :text
      add :field_16, :text
      add :field_17, :text
      add :field_18, :text
      add :field_19, :text
      add :field_20, :text
    end

    create table(:shops, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :region_id, :uuid, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :project_id, :uuid, null: false
      add :ambassador_id, :uuid, null: false
      add :outlet_id, :uuid, null: false
      add :field_1, :bigint
      add :field_2, :bigint
      add :field_3, :bigint
      add :field_4, :bigint
      add :field_5, :bigint
      add :field_6, :bigint
      add :field_7, :bigint
      add :field_8, :bigint
      add :field_9, :bigint
      add :field_10, :bigint
      add :field_11, :bigint
      add :field_12, :bigint
      add :field_13, :bigint
      add :field_14, :bigint
      add :field_15, :bigint
      add :field_16, :bigint
      add :field_17, :bigint
      add :field_18, :bigint
      add :field_19, :bigint
      add :field_20, :bigint
      add :total_sales, :bigint

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:registries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :project_id, :uuid, null: false
      add :ambassador_id, :uuid, null: false
      add :outlet_id, :uuid, null: false
      add :days_worked, :bigint, null: false, default: 0
      add :should_activate, :boolean, null: false, default: false
    end

    create table(:regions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:shops) do
      modify :region_id,
             references(:regions,
               column: :id,
               name: "shops_region_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:regions) do
      add :name, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:templates) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "templates_project_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:reports) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "reports_project_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :outlet_id,
             references(:shops,
               column: :id,
               name: "reports_outlet_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:registries) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "registries_project_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :outlet_id,
             references(:shops,
               column: :id,
               name: "registries_outlet_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:projects) do
      add :name, :text, null: false
      add :is_freezed, :boolean, null: false, default: false
    end

    create table(:managers, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:checkouts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ambassador_id, :uuid, null: false

      add :project_id,
          references(:projects,
            column: :id,
            name: "checkouts_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :outlet_id,
          references(:shops,
            column: :id,
            name: "checkouts_outlet_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :file, :map, null: false
      add :create_date, :date, null: false, default: fragment("CURRENT_DATE")
      add :create_time, :time, null: false
    end

    create table(:checkins, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ambassador_id, :uuid, null: false

      add :project_id,
          references(:projects,
            column: :id,
            name: "checkins_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :outlet_id,
          references(:shops,
            column: :id,
            name: "checkins_outlet_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :file, :map, null: false
      add :create_date, :date, null: false, default: fragment("CURRENT_DATE")
      add :create_time, :time, null: false
    end

    create table(:ambassadors, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :availability, :text, null: false, default: "Occupied"
      add :location, :text, null: false, default: "Not Set"
      add :total_days_worked, :bigint, null: false, default: 0
    end
  end

  def down do
    drop table(:ambassadors)

    drop constraint(:checkins, "checkins_project_id_fkey")

    drop constraint(:checkins, "checkins_outlet_id_fkey")

    drop table(:checkins)

    drop constraint(:checkouts, "checkouts_project_id_fkey")

    drop constraint(:checkouts, "checkouts_outlet_id_fkey")

    drop table(:checkouts)

    drop table(:managers)

    alter table(:projects) do
      remove :is_freezed
      remove :name
    end

    drop constraint(:registries, "registries_project_id_fkey")

    drop constraint(:registries, "registries_outlet_id_fkey")

    alter table(:registries) do
      modify :outlet_id, :uuid
      modify :project_id, :uuid
    end

    drop constraint(:reports, "reports_project_id_fkey")

    drop constraint(:reports, "reports_outlet_id_fkey")

    alter table(:reports) do
      modify :outlet_id, :uuid
      modify :project_id, :uuid
    end

    drop constraint(:templates, "templates_project_id_fkey")

    alter table(:templates) do
      modify :project_id, :uuid
    end

    drop table(:projects)

    alter table(:regions) do
      remove :updated_at
      remove :created_at
      remove :name
    end

    drop constraint(:shops, "shops_region_id_fkey")

    alter table(:shops) do
      modify :region_id, :uuid
    end

    drop table(:regions)

    drop table(:registries)

    drop table(:reports)

    drop table(:shops)

    drop table(:templates)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
