defmodule Marketingbsm.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :project_id, :uuid, null: false
      add :ambassador_id, :uuid, null: false
      add :outlet_id, :uuid, null: false
      add :field_1, :bigint
      add :field_2, :bigint
      add :field_3, :bigint
      add :field_4, :bigint
      add :field_5, :bigint
      add :field_6, :bigint
      add :field_7, :bigint
      add :field_8, :bigint
      add :field_9, :bigint
      add :field_10, :bigint
      add :field_11, :bigint
      add :field_12, :bigint
      add :field_13, :bigint
      add :field_14, :bigint
      add :field_15, :bigint
      add :field_16, :bigint
      add :field_17, :bigint
      add :field_18, :bigint
      add :field_19, :bigint
      add :field_20, :bigint
      add :total_sales, :bigint

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:registries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :project_id, :uuid, null: false
      add :ambassador_id, :uuid, null: false
      add :outlet_id, :uuid, null: false
      add :days_worked, :bigint, null: false, default: 0
      add :should_activate, :boolean, null: false, default: false
    end
  end

  def down do
    drop table(:registries)

    drop table(:reports)
  end
end
