defmodule Marketingbsm.Repo.Migrations.Checkoutsadded do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:checkouts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ambassador_id, :uuid, null: false
      add :project_id, :uuid, null: false
      add :outlet_id, :uuid, null: false
      add :file, :map, null: false
      add :create_date, :date, null: false, default: fragment("CURRENT_DATE")
      add :create_time, :time, null: false
    end
  end

  def down do
    drop table(:checkouts)
  end
end
