defmodule Marketingbsm.Repo.Migrations.Timedataddddddddd do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:checkins) do
      remove :create_time
      modify :create_date, :date, default: fragment("CURRENT_DATE")
    end
  end

  def down do
    alter table(:checkins) do
      modify :create_date, :date, default: nil
      add :create_time, :time, null: false
    end
  end
end
