defmodule Marketingbsm.Repo.Migrations.AddedCheckInResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:checkins, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ambassador_id, :uuid, null: false
      add :project_id, :uuid, null: false
      add :file_url, :text, null: false
    end
  end

  def down do
    drop table(:checkins)
  end
end
