defmodule Marketingbsm.Repo.Migrations.Timedataadded do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:checkins), :created_at, to: :create_date

    alter table(:checkins) do
      modify :create_date, :date, default: nil
      add :create_time, :time, null: false
    end
  end

  def down do
    alter table(:checkins) do
      remove :create_time
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    rename table(:checkins), :create_date, to: :created_at
  end
end
