defmodule Marketingbsm.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :project_id, :uuid, null: false
      add :field_1, :text
      add :field_2, :text
      add :field_3, :text
      add :field_4, :text
      add :field_5, :text
      add :field_6, :text
      add :field_7, :text
      add :field_8, :text
      add :field_9, :text
      add :field_10, :text
      add :field_11, :text
      add :field_12, :text
      add :field_13, :text
      add :field_14, :text
      add :field_15, :text
      add :field_16, :text
      add :field_17, :text
      add :field_18, :text
      add :field_19, :text
      add :field_20, :text
    end
  end

  def down do
    drop table(:templates)
  end
end
