defmodule Marketingbsm.Repo.Migrations.ChangedAmbassadorIdToId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ambassadors) do
      remove :ambassador_id
      modify :id, :uuid, default: nil
    end
  end

  def down do
    alter table(:ambassadors) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
      add :ambassador_id, :uuid, null: false, primary_key: true
    end
  end
end
